name: Main

on:
  push:
    branches:
      - master
  pull_request:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
          profile: minimal
          override: true

      - name: Format
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy --tests --features emergency-owner -- -D warnings

      - name: Test (no features)
        run: cargo test

      - name: Test (emergency-owner feature)
        run: cargo test --features emergency-owner
